name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        choco install awscli -y
        refreshenv

    - name: Deploy to Elastic Beanstalk
      run: |
        aws cloudformation deploy --template-file path/to/your/template.yaml --stack-name your-stack-name --capabilities CAPABILITY_NAMED_IAM
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

