name: Android CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 18.0.1.1
      uses: actions/setup-java@v2
      with:
        java-version: '18.0.1.1'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

 
