name: Android CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '31'
        


    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Run tests
      run: ./gradlew test
      
    - name: Run Python Script for Machine Learning Hybrid Model
      run: first.ipynb

 
