name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  ANDROID_COMPILE_SDK: 30
  ANDROID_BUILD_TOOLS: 30.0.2
  ANDROID_SDK_TOOLS: 7583922
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-and-deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '31'
        ndk-version: '21.4.7075529'
        build-tools-version: '31.0.0'
        licenses: "${{ secrets.ANDROID_LICENSES }}"
        
    - name: Add to PATH
      run: echo 'PATH="$PATH:$(pwd)"' >> $GITHUB_ENV
        
    - name: Add ./gradlew to PATH
      run: echo "::add-path::$(pwd)"
    
    - name: Initialize Gradle Build
      run: gradle init
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
      
    - name: Check code quality
      run: ./gradlew lintDebug lint-baseline.xml 


    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
          name: test-results
          path: |
            app/build/reports/tests/testDebugUnitTest
            app/build/reports/androidTests/connected/flavors/Debug/index.html
            app/build/reports/lint-results.xml



      
 

 
